#ifndef RETURN_VALUES_H
#define RETURN_VALUES_H

#define CORRECT_MOVE 0
#define CAN_NOT_MAKE_ANY_MOVE 1
#define INPUT_FILE_ERROR 2
#define INTERNAL_PROGRAM_ERROR 3
#define EMPTY_FILE 4

#define MAX_HEIGHT 26
#define MAX_WIDTH 50

#define MAX_PENGUINS 4

#endif