#ifndef RETURN_VALUES_H
#define RETURN_VALUES_H

#define CORRECT_MOVE 0
#define CAN_NOT_MAKE_ANY_MOVE 1
#define INPUT_FILE_ERROR 2
#define INTERNAL_PROGRAM_ERROR 3

#define EMPTY_FILE 4
#define GENERATING_BOARD_FAILURE 5
#define GENERATING_BOARD_SUCCESS 6
#define LOADING_DATA_FAILURE 7
#define LOADING_DATA_SUCCESS 8
#define WRONG_CMD_PARAMETERS 9
#define PLACEMENT_FAILURE 10
#define PLACEMENT_SUCCESS 11

#define MAX_HEIGHT 26
#define MAX_WIDTH 50
#define MAX_ID_LENGTH 100
#define MAX_FILENAME_LENGTH 100
#define MAX_PENGUINS 4

#endif